name: Work Stats Readme

on:
  # Schedule daily updates
  # Run at 12AM IST
  schedule: [{cron: "30 18 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: GITHUB_README
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.WAKATIME_API_KEY }}

          # Options
          user: Abhishek9503
          template: classic
          base: header, activity, community, repositories, metadata
          config_padding: 0, 0
          config_timezone: Asia/Calcutta
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 3
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: Abhishek9503

          output_action: gist
          committer_gist: 3e153d0295a3f10c924e657735f8eb9a
